################################################################
# +----------------------------------------------------------+ #
# |                   qMobsDropEggs Config                   | #
# |   Source:   https://github.com/QarthO/qMobsDropEggs/     | #
# |   Download: https://modrinth.com/plugin/qMobsDropEggs/   | #
# |   Donate:   https://quartzdev.gg/donate/                 | #
# +----------------------------------------------------------+ #
################################################################

version: ${project.version}
check-updates: true

# Will only drop an egg if killed by a player
requires-player-killer: true
# Will check if the player has the permission: 'qMDE.player'
killer-requires-permission: true

# Mobs won't drop eggs if their spawn reason matches anything in this list
# If you want this empty set this to >> blacklist-spawn-reasons: []
# SpawnReason List: https://jd.papermc.io/paper/1.16/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
blacklisted-spawn-reasons:
  - SPAWNER

# If set to true, this will treat the above spawn-reason list as a whitelist
invert-blacklisted-spawn-reasons: false

# Name of the world where the plugin will be disabled
disabled-worlds:
  - hub
  - creative

# Should the drop chance be increased by looting
# Each level of looting adds 1% to the drop-chance
factor-looting: true
# Changes the drop chance calculation when factoring in looting
# But only if it is below the breakpoint
# Now final drop chance = drop chance * (1 + looting level)
# Example: drop chance of .05% with looting 3
#         0.05% * (1 + 3) = .2%
# complex-looting only makes sense for smaller numbers you want to keep small
# factor-looting must be set to true
complex-looting: true
complex-looting-breakpoint: 1

# The odds of a spawn egg from dropping when a player kills a mob
# 1 would be 1% chance, (supports decimals)
drop-chance:
  default: 1
  mobs:
    SHULKER: .01
    IRON_GOLEM: .1
#    PHANTOM: 10
#    VILLAGER: .1

# Prevent certain mobs from dropping spawn eggs
# Spawn Egg list: https://minecraft.wiki/w/Spawn_Egg
# EntityType format: https://jd.papermc.io/paper/1.20/org/bukkit/entity/EntityType.html
blacklisted-mobs:
  - ENDER_DRAGON
  - WARDEN
  - WITHER
  - WANDERING_TRADER